# Generated by Django 3.2 on 2021-05-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='news_pics'),
        ),
    ]
