# Generated by Django 3.2 on 2021-05-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_campaign_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='tags',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='theme',
            field=models.CharField(choices=[('all', 'All'), ('education', 'Education'), ('electronics', 'Electronics'), ('entertainment', 'Entertainment'), ('sport', 'Sport'), ('IT', 'IT')], default='all', max_length=255),
        ),
    ]
